export GTK_THEME=Juno-ocean
# export PATH=~/.npm-global/bin:$PATH
# DRI_PRIME=1 
# NPM_CONFIG_PREFIX=~/.npm-global
PATH="$HOME/.local/bin:$PATH"
#LIBSEAT_BACKEND=logind
PATH="/opt/flutter/bin:$PATH"
# export PATH=~/.npm-global/bin:$PATH
# export npm_config_prefix="$HOME/.local"
# export QT_QPA_PLATFORM=wayland
export GDK_BACKEND=wayland,x11
export QT_QPA_PLATFORM="wayland;xcb"
# export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland 
export MOZ_ENABLE_WAYLAND=1
# export XDG_CURRENT_DESKTOP=Hyprland
# export XDG_SESSION_TYPE=wayland
# export XDG_SESSION_DESKTOP=Hyprland
# export QT_AUTO_SCREEN_SCALE_FACTOR=1
# export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export LIBVA_DRIVER_NAME=radeonsi
export CHROME_EXECUTABLE=/usr/bin/brave-browser
export QT_QPA_PLATFORMTHEME=qt6ct
export export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true'
# MESA_WHICH_LLVM=2
# export WLR_DRM_DEVICES=/dev/dri/card1:/dev/dri/card0
# export WLR_DRM_DEVICES=/dev/dri/card0:/dev/dri/card1
export WLR_DRM_DEVICES=/dev/dri/card0
# export WLR_DRM_DEVICES=/dev/dri/card1
